# -*- coding: utf-8 -*-
"""ETF_yfinance_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acC4Rj-4zTjRDynHYvbPr51r5puZyTeW
"""

import yfinance as yf
import pandas as pd

# Define ticker and date range
ticker = "SILVERIETF.NS"
start_date = "2022-01-01"
end_date = "2025-08-30"  # today's date

# Download monthly data
df = yf.download(ticker, start=start_date, end=end_date, interval="1mo")

# Reset index so Date is a column
df.reset_index(inplace=True)

# If columns are MultiIndex, flatten them
if isinstance(df.columns, pd.MultiIndex):
    df.columns = [' '.join(col).strip() if isinstance(col, tuple) else col for col in df.columns]

# Format date and round prices
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date']).dt.strftime('%Y-%m-%d')
df = df.round(2)

# Save to Excel
df.to_excel("silver_etf_monthly.xlsx", index=False)

print("Excel file saved as silver_etf_monthly.xlsx")